/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs480.project1.gradebook;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Phuoc
 */
public class GradeBookApp extends javax.swing.JFrame {

    
    public static final String FILENAME = "course.txt";
    public static String[] courseArray;
    GradeBook cd = new GradeBook();
    ArrayList<String> allData;
    
    /**
     * Creates new form GradeBookApp
     */
    public GradeBookApp() {
        initComponents();
        myInitComponents();
        
        courseArray = cd.readTextFile(0).toArray(new String[cd.readTextFile(0).size()]);
        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courseArray));
        
        allData = cd.readTextFile();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseComboBox = new javax.swing.JComboBox<>();
        delCourseButton = new javax.swing.JButton();
        addStudentButton = new javax.swing.JButton();
        delStudentButton = new javax.swing.JButton();
        addAssignButton = new javax.swing.JButton();
        finalGradeButton = new javax.swing.JButton();
        exportCSVButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        courseTextField = new javax.swing.JTextField();
        addCourseButton = new javax.swing.JButton();
        firstName = new javax.swing.JTextField();
        middleName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        courseLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        courseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboBoxActionPerformed(evt);
            }
        });

        delCourseButton.setText("Delete Course");
        delCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delCourseButtonActionPerformed(evt);
            }
        });

        addStudentButton.setText("Add Student");

        delStudentButton.setText("Delete Student");

        addAssignButton.setText("Add Assignment");

        finalGradeButton.setText("Final Grade");

        exportCSVButton.setText("Export to CSV");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Last Name", "Middle Name", "First Name", "Assignment", "Assignment", "Weight", "Final Grade"
            }
        ));
        jScrollPane1.setViewportView(table);

        courseTextField.setText("Course");
        courseTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseTextFieldActionPerformed(evt);
            }
        });

        addCourseButton.setText("Add Course");
        addCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseButtonActionPerformed(evt);
            }
        });

        firstName.setText("First Name");

        middleName.setText("Middle Name");

        lastName.setText("Last Name");

        courseLabel.setText("Course:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(middleName, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(courseLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(courseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(delCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addAssignButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(courseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(254, 254, 254)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(exportCSVButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(finalGradeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(courseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCourseButton)
                            .addComponent(exportCSVButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(middleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addStudentButton)
                        .addComponent(delStudentButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalGradeButton)
                    .addComponent(addAssignButton)
                    .addComponent(delCourseButton)
                    .addComponent(courseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myInitComponents(){
        
    }
    
    private void courseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseTextFieldActionPerformed

    private void addCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseButtonActionPerformed
       if(courseTextField.getText().length() == 0)
        {
            String message, title;
            
            message = "You must enter a course in the Text Field.";
            title = "Missing a course";
            
            JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
        }
       for (int i = 0; i < courseArray.length; i++){
             if(courseTextField.getText().contains(courseArray[i])){
                        String message = "Course already existed. Cannnot add.";
                        String title = "Existed Course";
                        JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
                  courseTextField.setText("");
                 }
             }
        
        
        if (courseTextField.getText().length() != 0) {
            
            if(courseTextField.toString().contains(courseTextField.getText())) {
                String message, title;
                
                message = "Course already existed. Cannnot add.";
                title = "Existed Course";
            
                JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
                courseTextField.setText("");
            } else {
                        String newStd = courseTextField.getText() + ", ";
                        allData.add(newStd);
                        StringBuilder sb = new StringBuilder();
                        for (String string : allData) {
                            sb.append(string);
                            sb.append("\n");
                        }

                    GradeBook.writeToFile(sb, FILENAME, false);
                    loadData();
                    courseTextField.setText("");         
                }
        }
       
    }//GEN-LAST:event_addCourseButtonActionPerformed

    private void courseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboBoxActionPerformed
       
        String selectedCourse = courseComboBox.getSelectedItem().toString(); 
        //studentsArray = new String[cd.getStudents(selectedCourse).size()];
        //studentsArray = cd.getStudents(selectedCourse).toArray(coursesArray);
    }//GEN-LAST:event_courseComboBoxActionPerformed

    private void delCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delCourseButtonActionPerformed
        // TODO add your handling code here:
        if(courseComboBox.getItemCount() == 0)
        {
            String message = "There is no more course to delete";
            String title = "No more course";
            
            JOptionPane.showMessageDialog(this, message, title, JOptionPane.ERROR_MESSAGE);
        }
        else
        {    
            int choice = JOptionPane.showConfirmDialog(null, 
                    "Are you sure to delete " + courseComboBox.getSelectedItem() + " and its associated students?" 
                            , "Delete student(s)", JOptionPane.INFORMATION_MESSAGE );
            StringBuilder sb = new StringBuilder();
            if (choice == 0) {
                boolean myBoo = true;
                // students = sel + "," + students;
                for (String j : allData) {
                    myBoo = true;

                    if (!j.contains( courseComboBox.getSelectedItem().toString())) {
                    sb.append(j + "\n");
                    }

                }
            GradeBook.writeToFile(sb, FILENAME, false);
            loadData();
            }
        }
        
    }//GEN-LAST:event_delCourseButtonActionPerformed

    
    public void loadData()
    {
        //coursesArray = new String[cd.readTextFile(0).size()];
        //coursesArray = cd.readTextFile(0).toArray(coursesArray);
        courseArray = cd.readTextFile(0).toArray(new String[cd.readTextFile(0).size()]);
        courseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courseArray));
    
        String selectedCourse = courseComboBox.getSelectedItem().toString();   
       // studentsArray = cd.getStudents(selectedCourse).toArray(new String[cd.getStudents(selectedCourse).size()]);
        //studentsArray = new String[cd.getStudents(selectedCourse).size()];
        //studentsArray = cd.getStudents(selectedCourse).toArray(coursesArray);
        
        allData = cd.readTextFile();
      //  studentList.setModel(new javax.swing.DefaultComboBoxModel(studentsArray));
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeBookApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeBookApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeBookApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeBookApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GradeBookApp frame = new GradeBookApp();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
                frame.setTitle("Grade Book");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAssignButton;
    private javax.swing.JButton addCourseButton;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JComboBox<String> courseComboBox;
    private javax.swing.JLabel courseLabel;
    private javax.swing.JTextField courseTextField;
    private javax.swing.JButton delCourseButton;
    private javax.swing.JButton delStudentButton;
    private javax.swing.JButton exportCSVButton;
    private javax.swing.JButton finalGradeButton;
    private javax.swing.JTextField firstName;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField middleName;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
